### ISSUE TITLE
Issues With CDK deploy

### ISSUE THREAD

**Issue by artizani** [alexhddev/CDK-course-resources#1]
DataStack: creating CloudFormation changeset...
14:21:13 | CREATE_FAILED        | AWS::S3::BucketPolicy | SpaceFinderFrontendPolicyFFE9DC58
API: s3:PutBucketPolicy Access Denied

 ❌  DataStack failed: Error: The stack named DataStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: API: s3:PutBucketPolicy Access Denied
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:380:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack2 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:383:145458)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:383:128776
    at async run (/usr/local/lib/node_modules/aws-cdk/lib/index.js:383:126782)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named DataStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: API: s3:PutBucketPolicy Access Denied
    at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/index.js:383:129083)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:383:147507)
    at async exec4 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:438:51799)

Stack Deployments Failed: Error: The stack named DataStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: API: s3:PutBucketPolicy Access Denied

**Comment by artizani** [comment]
I get the error below when I try to deploy the cdk. I'm following your course [AWS & Typescript Masterclass - CDK V2, Serverless, React](https://www.udemy.com/course/aws-typescript-cdk-serverless-react/).  @alexhddev

**Comment by alexhddev** [comment]
Fixed with https://github.com/alexhddev/CDK-course-resources/pull/2

**Comment by artizani** [comment]
@alexhddev  new issues
  You can mark the path "aws-xray-sdk-core" as external to exclude it from the bundle, which will
  remove this error.

1 error
/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2
`),localBundling=options.local?.tryBundle(bundleDir,options),!localBundling){const assetStagingOptions={sourcePath:this.sourcePath,bundleDir,...options};switch(options.bundlingFileAccess){case bundling_1.BundlingFileAccess.VOLUME_COPY:new asset_staging_1.AssetBundlingVolumeCopy(assetStagingOptions).run();break;case bundling_1.BundlingFileAccess.BIND_MOUNT:default:new asset_staging_1.AssetBundlingBindMount(assetStagingOptions).run();break}}}catch(err){const bundleErrorDir=bundleDir+"-error";throw fs.existsSync(bundleErrorDir)&&fs.removeSync(bundleErrorDir),fs.renameSync(bundleDir,bundleErrorDir),new Error(`Failed to bundle asset ${this.node.path}, bundle output is located at ${bundleErrorDir}: ${err}`)}if(fs_1.FileSystem.isEmpty(bundleDir)){const outputDir=localBundling?bundleDir:AssetStaging.BUNDLING_OUTPUT_DIR;throw new Error(`Bundling did not produce any output. Check that content is written to ${outputDir}.`)}}calculateHash(hashType,bundling,outputDir){if(hashType==assets_1.AssetHashType.CUSTOM||hashType==assets_1.AssetHashType.SOURCE&&bundling){const hash=crypto.createHash("sha256");return hash.update(this.customSourceFingerprint??fs_1.FileSystem.fingerprint(this.sourcePath,this.fingerprintOptions)),bundling&&hash.update(JSON.stringify(bundling)),hash.digest("hex")}switch(hashType){case assets_1.AssetHashType.SOURCE:return fs_1.FileSystem.fingerprint(this.sourcePath,this.fingerprintOptions);case assets_1.AssetHashType.BUNDLE:case assets_1.AssetHashType.OUTPUT:if(!outputDir)throw new Error(`Cannot use \`${hashType}\` hash type when \`bundling\` is not specified.`);return fs_1.FileSystem.fingerprint(outputDir,this.fingerprintOptions);default:throw new Error("Unknown asset hash type.")}}}_a=JSII_RTTI_SYMBOL_1,AssetStaging[_a]={fqn:"aws-cdk-lib.AssetStaging",version:"2.72.1"},AssetStaging.BUNDLING_INPUT_DIR="/asset-input",AssetStaging.BUNDLING_OUTPUT_DIR="/asset-output",AssetStaging.assetCache=new cache_1.Cache,exports.AssetStaging=AssetStaging;function renderAssetFilename(assetHash,extension=""){return`asset.${assetHash}${extension}`}function determineHashType(assetHashType,customSourceFingerprint){const hashType=customSourceFingerprint?assetHashType??assets_1.AssetHashType.CUSTOM:assetHashType??assets_1.AssetHashType.SOURCE;if(customSourceFingerprint&&hashType!==assets_1.AssetHashType.CUSTOM)throw new Error(`Cannot specify \`${assetHashType}\` for \`assetHashType\` when \`assetHash\` is specified. Use \`CUSTOM\` or leave \`undefined\`.`);if(hashType===assets_1.AssetHashType.CUSTOM&&!customSourceFingerprint)throw new Error("`assetHash` must be specified when `assetHashType` is set to `AssetHashType.CUSTOM`.");return hashType}function calculateCacheKey(props){return crypto.createHash("sha256").update(JSON.stringify(sortObject(props))).digest("hex")}function sortObject(object){if(typeof object!="object"||object instanceof Array)return object;const ret={};for(const key of Object.keys(object).sort())ret[key]=sortObject(object[key]);return ret}function singleArchiveFile(directory){if(!fs.existsSync(directory))throw new Error(`Directory ${directory} does not exist.`);if(!fs.statSync(directory).isDirectory())throw new Error(`${directory} is not a directory.`);const content=fs.readdirSync(directory);if(content.length===1){const file=path.join(directory,content[0]),extension=getExtension(content[0]).toLowerCase();if(fs.statSync(file).isFile()&&ARCHIVE_EXTENSIONS.includes(extension))return file}}function determineBundledAsset(bundleDir,outputType){const archiveFile=singleArchiveFile(bundleDir);switch(outputType===bundling_1.BundlingOutput.AUTO_DISCOVER&&(outputType=archiveFile?bundling_1.BundlingOutput.ARCHIVED:bundling_1.BundlingOutput.NOT_ARCHIVED),outputType){case bundling_1.BundlingOutput.NOT_ARCHIVED:return{path:bundleDir,packaging:assets_1.FileAssetPackaging.ZIP_DIRECTORY};case bundling_1.BundlingOutput.ARCHIVED:if(!archiveFile)throw new Error("Bundling output directory is expected to include only a single archive file when `output` is set to `ARCHIVED`");return{path:archiveFile,packaging:assets_1.FileAssetPackaging.FILE,extension:getExtension(archiveFile)}}}function getExtension(source){for(const ext of ARCHIVE_EXTENSIONS)if(source.toLowerCase().endsWith(ext))return ext;return path.extname(source)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ^
Error: Failed to bundle asset LambdaStack/SpacesLambda/Code/Stage, bundle output is located at /Users/dreamer/Development/Aws/CDK-course-resources/space-finder/cdk.out/bundling-temp-df0a88b2e908dad08cb7608e07ee6c331e6f5a81d45079531aed572c2333c77f-error: Error: bash -c npx --no-install esbuild --bundle "/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/src/services/spaces/handler.ts" --target=node18 --platform=node --outfile="/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/cdk.out/bundling-temp-df0a88b2e908dad08cb7608e07ee6c331e6f5a81d45079531aed572c2333c77f/index.js" --external:@aws-sdk/* run in directory /Users/dreamer/Development/Aws/CDK-course-resources/space-finder exited with status 1
    at AssetStaging.bundle (/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2:603)
    at AssetStaging.stageByBundling (/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:4544)
    at stageThisAsset (/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2005)
    at Cache.obtain (/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/node_modules/aws-cdk-lib/core/lib/private/cache.js:1:242)
    at new AssetStaging (/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2400)
    at new Asset (/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:736)
    at AssetCode.bind (/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/node_modules/aws-cdk-lib/aws-lambda/lib/code.js:1:4628)
    at new Function (/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:7479)
    at new NodejsFunction (/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.js:1:1171)
    at new LambdaStack (/Users/dreamer/Development/Aws/CDK-course-resources/space-finder/src/infra/stacks/LambdaStack.ts:22:30)
